# Generated by Django 5.2.7 on 2025-11-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0002_remove_cargo_id_remove_clinica_id_remove_endereco_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='id_cargo',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='id_clinica',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='id_endereco',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='id_especialidade',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='id_gestor',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id_medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='id_prontuario',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='id_servico',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='id_setor',
        ),
        migrations.AddField(
            model_name='cargo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='medico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='servico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='setor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.setor'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='conta_bancaria_juridica',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.endereco'),
        ),
        migrations.AlterField(
            model_name='clinicaservico',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.clinica'),
        ),
        migrations.AlterField(
            model_name='clinicaservico',
            name='forma_pagamento',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='clinicaservico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='clinicaservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.servico'),
        ),
        migrations.AlterField(
            model_name='especialidademedico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidademedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.medico'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.cargo'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.clinica'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medico',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.clinica'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm_cro',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='medico',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='data_modificacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.paciente'),
        ),
        migrations.AlterField(
            model_name='prontuariomedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.medico'),
        ),
        migrations.AlterField(
            model_name='prontuariomedico',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.prontuario'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.especialidade'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.medico'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.paciente'),
        ),
        migrations.AlterModelTable(
            name='cargo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='clinica',
            table=None,
        ),
        migrations.AlterModelTable(
            name='clinicaservico',
            table=None,
        ),
        migrations.AlterModelTable(
            name='endereco',
            table=None,
        ),
        migrations.AlterModelTable(
            name='especialidade',
            table=None,
        ),
        migrations.AlterModelTable(
            name='especialidademedico',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gestor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='medico',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paciente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prontuario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prontuariomedico',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servico',
            table=None,
        ),
        migrations.AlterModelTable(
            name='setor',
            table=None,
        ),
    ]
