# Generated by Django 5.2.7 on 2025-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0003_remove_cargo_id_cargo_remove_clinica_id_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clinicas/'),
        ),
    ]
