# Generated by Django 5.2.7 on 2025-11-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=60)),
                ('quadra', models.CharField(max_length=60)),
                ('rua', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=85)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=45)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(max_length=14)),
                ('conta_bancaria_juridica', models.CharField(max_length=45)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=85)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('sexo', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1)),
                ('email', models.EmailField(max_length=45)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=14)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.cargo')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=85)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('sexo', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1)),
                ('email', models.EmailField(max_length=45)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(max_length=30)),
                ('crm_cro', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=14)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadeMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('prescricao', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_procedimento', models.CharField(max_length=100)),
                ('data_modificacao', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ProntuarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.medico')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(max_length=45)),
                ('motivo', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], max_length=10)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('forma_pagamento', models.CharField(max_length=45)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.clinica')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.servico')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.setor'),
        ),
    ]
