# Generated by Django 5.2.10 on 2026-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproAvaliacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_postagem', models.DateTimeField()),
                ('clinica_id', models.BigIntegerField()),
                ('medico_id', models.BigIntegerField()),
                ('paciente_id', models.BigIntegerField()),
                ('consulta_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'odontopro_avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproClinica',
            fields=[
                ('cnpj', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=85)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('telefone', models.CharField(max_length=14)),
                ('conta_bancaria_juridica', models.CharField(max_length=45)),
                ('endereco_id', models.BigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagem', models.CharField(blank=True, max_length=100, null=True)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('num_avaliacoes', models.IntegerField()),
                ('preco_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'odontopro_clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproClinicaimagem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagem', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField()),
                ('clinica_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'odontopro_clinicaimagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproClinicaservico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('forma_pagamento', models.CharField(max_length=45)),
                ('clinica_id', models.BigIntegerField()),
                ('servico_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'odontopro_clinicaservico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproConsulta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('especialidade', models.CharField(blank=True, max_length=120, null=True)),
                ('data_hora', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField()),
                ('clinica_id', models.BigIntegerField()),
                ('medico_id', models.BigIntegerField()),
                ('paciente_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'odontopro_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproDiasemanadisponivel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('clinica_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'odontopro_diasemanadisponivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproEndereco',
            fields=[
                ('cep', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=60)),
                ('quadra', models.CharField(max_length=60)),
                ('rua', models.CharField(max_length=60)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('cidade', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'odontopro_endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproEspecialidade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'odontopro_especialidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproGerenciamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=85)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField()),
                ('ativo', models.IntegerField()),
                ('clinica_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'odontopro_gerenciamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproGerenciamentoPermissoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gerenciamento_id', models.BigIntegerField()),
                ('permissao_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'odontopro_gerenciamento_permissoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproHorarioaberto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('dia_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'odontopro_horarioaberto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproMedico',
            fields=[
                ('nome', models.CharField(max_length=85)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=45)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(max_length=255)),
                ('crm_cro', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=14)),
                ('clinica_id', models.BigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('num_avaliacoes', models.IntegerField()),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'odontopro_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproMedicoEspecialidades',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medico_id', models.BigIntegerField()),
                ('especialidade_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'odontopro_medico_especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproMedicohorario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('medico_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'odontopro_medicohorario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproPaciente',
            fields=[
                ('nome', models.CharField(max_length=85)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=14)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'odontopro_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproPermissao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'odontopro_permissao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontoproServico',
            fields=[
                ('tipo', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=200)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'odontopro_servico',
                'managed': False,
            },
        ),
    ]
