# Generated by Django 5.2.7 on 2025-11-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='id',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='id',
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_cargo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='clinica',
            name='id_clinica',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='endereco',
            name='id_endereco',
            field=models.AutoField(db_column='id_endereço', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='id_especialidade',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gestor',
            name='id_gestor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medico',
            name='id_medico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_paciente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='id_prontuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='servico',
            name='id_servico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='setor',
            name='id_setor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(db_column='SETOR_id_setor', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.setor'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='conta_bancaria_juridica',
            field=models.CharField(db_column='conta_bancaria_Juridica', max_length=45),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='endereco',
            field=models.ForeignKey(db_column='ENDERECO_id_endereço', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.endereco'),
        ),
        migrations.AlterField(
            model_name='clinicaservico',
            name='clinica',
            field=models.ForeignKey(db_column='CLINICA_id_clinica', on_delete=django.db.models.deletion.CASCADE, to='odontoPro.clinica'),
        ),
        migrations.AlterField(
            model_name='clinicaservico',
            name='forma_pagamento',
            field=models.CharField(db_column='forma_de_pagamento', max_length=45),
        ),
        migrations.AlterField(
            model_name='clinicaservico',
            name='preco',
            field=models.DecimalField(db_column='preço', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='clinicaservico',
            name='servico',
            field=models.ForeignKey(db_column='SERVICO_id_servico', on_delete=django.db.models.deletion.CASCADE, to='odontoPro.servico'),
        ),
        migrations.AlterField(
            model_name='especialidademedico',
            name='especialidade',
            field=models.ForeignKey(db_column='ESPECIALIDADES_id_especialidade', on_delete=django.db.models.deletion.CASCADE, to='odontoPro.especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidademedico',
            name='medico',
            field=models.ForeignKey(db_column='MEDICO_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='odontoPro.medico'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='cargo',
            field=models.ForeignKey(db_column='CARGOS_id_cargo', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.cargo'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='clinica',
            field=models.ForeignKey(db_column='CLINICA_id_clinica', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.clinica'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='data_nascimento',
            field=models.DateField(blank=True, db_column='dataNasc', null=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='email',
            field=models.EmailField(db_column='e-mail', max_length=45),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='medico',
            name='clinica',
            field=models.ForeignKey(db_column='CLINICA_id_clinica', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.clinica'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm_cro',
            field=models.CharField(db_column='CRM/CRO', max_length=60),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(blank=True, db_column='dataNasc', null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(db_column='e-mail', max_length=45),
        ),
        migrations.AlterField(
            model_name='medico',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, db_column='dataNasc', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(db_column='e-mail', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='data_modificacao',
            field=models.DateField(db_column='data_modificação'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(db_column='PACIENTE_id_paciente', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.paciente'),
        ),
        migrations.AlterField(
            model_name='prontuariomedico',
            name='medico',
            field=models.ForeignKey(db_column='MEDICO_id_medico_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='odontoPro.medico'),
        ),
        migrations.AlterField(
            model_name='prontuariomedico',
            name='prontuario',
            field=models.ForeignKey(db_column='PRONTUARIO_id_prontuario', on_delete=django.db.models.deletion.CASCADE, to='odontoPro.prontuario'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='especialidade',
            field=models.ForeignKey(db_column='ESPECIALIDADES_id_especialidade', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.especialidade'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='medico',
            field=models.ForeignKey(db_column='MEDICO_id_usuario', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.medico'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='paciente',
            field=models.ForeignKey(db_column='PACIENTE_id_paciente1', on_delete=django.db.models.deletion.PROTECT, to='odontoPro.paciente'),
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='CARGOS',
        ),
        migrations.AlterModelTable(
            name='clinica',
            table='CLINICA',
        ),
        migrations.AlterModelTable(
            name='clinicaservico',
            table='CLINICA_SERVICO',
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='ENDERECO',
        ),
        migrations.AlterModelTable(
            name='especialidade',
            table='ESPECIALIDADES',
        ),
        migrations.AlterModelTable(
            name='especialidademedico',
            table='ESPECIALIDADES_MEDICO',
        ),
        migrations.AlterModelTable(
            name='gestor',
            table='GESTOR',
        ),
        migrations.AlterModelTable(
            name='medico',
            table='MEDICO',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='PACIENTE',
        ),
        migrations.AlterModelTable(
            name='prontuario',
            table='PRONTUARIO',
        ),
        migrations.AlterModelTable(
            name='prontuariomedico',
            table='PRONTUARIO_MEDICO',
        ),
        migrations.AlterModelTable(
            name='servico',
            table='SERVICO',
        ),
        migrations.AlterModelTable(
            name='setor',
            table='SETOR',
        ),
    ]
