# Generated by Django 5.2.11 on 2026-02-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0002_avaliacao_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_clinica', to='odontoPro.clinica'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_medico', to='odontoPro.medico'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_paciente', to='odontoPro.paciente'),
        ),
    ]
