# Generated by Django 5.2.10 on 2026-03-11 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_postagem'],
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=85)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('telefone', models.CharField(max_length=14)),
                ('conta_bancaria_juridica', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinicas/logo/')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='clinicas/')),
                ('preco_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=3, null=True)),
                ('num_avaliacoes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='clinicas/capa/')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='odontoPro.clinica')),
            ],
            options={
                'verbose_name': 'Imagem da Clínica',
                'verbose_name_plural': 'Imagens da Clínica',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ClinicaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('forma_pagamento', models.CharField(max_length=45)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('especialidade', models.CharField(blank=True, max_length=120, null=True)),
                ('data_hora', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='agendada', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='DiaSemanaDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('domingo', 'Domingo'), ('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_semana', to='odontoPro.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=60)),
                ('quadra', models.CharField(max_length=60)),
                ('rua', models.CharField(max_length=60)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('cidade', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=85)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAberto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='odontoPro.diasemanadisponivel')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=85)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('sexo', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1)),
                ('email', models.EmailField(max_length=45)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(max_length=255)),
                ('crm_cro', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=14)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=3, null=True)),
                ('num_avaliacoes', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='medicos/')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('domingo', 'Domingo'), ('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horário do Médico',
                'verbose_name_plural': 'Horários do Médico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=85)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=14)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/')),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='OdontoproAvaliacao',
        ),
        migrations.DeleteModel(
            name='OdontoproClinica',
        ),
        migrations.DeleteModel(
            name='OdontoproClinicaimagem',
        ),
        migrations.DeleteModel(
            name='OdontoproClinicaservico',
        ),
        migrations.DeleteModel(
            name='OdontoproConsulta',
        ),
        migrations.DeleteModel(
            name='OdontoproDiasemanadisponivel',
        ),
        migrations.DeleteModel(
            name='OdontoproEndereco',
        ),
        migrations.DeleteModel(
            name='OdontoproEspecialidade',
        ),
        migrations.DeleteModel(
            name='OdontoproGerenciamento',
        ),
        migrations.DeleteModel(
            name='OdontoproGerenciamentoPermissoes',
        ),
        migrations.DeleteModel(
            name='OdontoproHorarioaberto',
        ),
        migrations.DeleteModel(
            name='OdontoproMedico',
        ),
        migrations.DeleteModel(
            name='OdontoproMedicoEspecialidades',
        ),
        migrations.DeleteModel(
            name='OdontoproMedicohorario',
        ),
        migrations.DeleteModel(
            name='OdontoproPaciente',
        ),
        migrations.DeleteModel(
            name='OdontoproPermissao',
        ),
        migrations.DeleteModel(
            name='OdontoproServico',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_clinica', to='odontoPro.clinica'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='odontoPro.consulta'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.endereco'),
        ),
        migrations.AddField(
            model_name='gerenciamento',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerentes', to='odontoPro.clinica'),
        ),
        migrations.AddField(
            model_name='medico',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontoPro.clinica'),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(related_name='medicos', to='odontoPro.especialidade'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.medico'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_medico', to='odontoPro.medico'),
        ),
        migrations.AddField(
            model_name='medicohorario',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_medico', to='odontoPro.medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontoPro.paciente'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_paciente', to='odontoPro.paciente'),
        ),
        migrations.AddField(
            model_name='gerenciamento',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='usuarios_gerenciamento', to='odontoPro.permissao'),
        ),
        migrations.AddField(
            model_name='clinicaservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.servico'),
        ),
    ]
