# Generated by Django 5.2.10 on 2026-04-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0003_avaliacao_clinica_clinicaimagem_clinicaservico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('email', 'Email'), ('outro', 'Outro')], max_length=20)),
                ('valor', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=120, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='odontoPro.clinica')),
            ],
            options={
                'verbose_name': 'Contato da Clínica',
                'verbose_name_plural': 'Contatos da Clínica',
            },
        ),
    ]
