# Generated by Django 5.2.10 on 2026-04-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0004_clinica_ativo_especialidade_preco_medico_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontoPro.especialidade'),
        ),
        migrations.CreateModel(
            name='MedicoEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_especialidades', to='odontoPro.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_especialidades', to='odontoPro.medico')),
            ],
            options={
                'verbose_name': 'Especialidade do Médico',
                'verbose_name_plural': 'Especialidades do Médico',
                'unique_together': {('medico', 'especialidade')},
            },
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(related_name='medicos', through='odontoPro.MedicoEspecialidade', to='odontoPro.especialidade'),
        ),
    ]
