# Generated by Django 5.2.10 on 2026-04-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0005_alter_clinica_descricao_alter_consulta_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='odontoPro.clinica'),
        ),
        migrations.DeleteModel(
            name='ClinicaServico',
        ),
    ]
