# Generated by Django 5.2.7 on 2025-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0005_diadisponivel_horariodisponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='num_avaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinica',
            name='preco_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
