# Generated by Django 5.2.7 on 2025-11-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0006_clinica_avaliacao_clinica_num_avaliacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='diadisponivel',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='especialidademedico',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='especialidademedico',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='prontuariomedico',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='prontuariomedico',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='status',
        ),
        migrations.CreateModel(
            name='DiaSemanaDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('domingo', 'Domingo'), ('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_semana', to='odontoPro.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAberto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='odontoPro.diasemanadisponivel')),
            ],
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='DiaDisponivel',
        ),
        migrations.DeleteModel(
            name='HorarioDisponivel',
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
        migrations.DeleteModel(
            name='EspecialidadeMedico',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
        migrations.DeleteModel(
            name='Prontuario',
        ),
        migrations.DeleteModel(
            name='ProntuarioMedico',
        ),
    ]
