# Generated by Django 5.2.10 on 2026-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0006_especialidade_clinica_delete_clinicaservico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidades',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS odontoPro_medicoespecialidade",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='MedicoEspecialidade',
                ),
            ],
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS odontoPro_medico_especialidades",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='odontoPro.especialidade'),
        ),
    ]
