# Generated by Django 5.2.7 on 2025-11-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0008_especialidade_medico_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='num_avaliacoes',
            field=models.IntegerField(default=0),
        ),
    ]
