# Generated by Django 5.2.7 on 2025-12-01 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0009_medico_avaliacao_medico_num_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicos/'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nome',
            field=models.CharField(max_length=85),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('especialidade', models.CharField(blank=True, max_length=120, null=True)),
                ('data_hora', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='agendada', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.clinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontoPro.medico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontoPro.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('domingo', 'Domingo'), ('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_medico', to='odontoPro.medico')),
            ],
            options={
                'verbose_name': 'Horário do Médico',
                'verbose_name_plural': 'Horários do Médico',
            },
        ),
    ]
