# Generated by Django 5.2.10 on 2026-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0009_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='clinicas/logo/'),
        ),
    ]
