# Generated by Django 5.2.10 on 2026-01-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0010_medico_foto_alter_clinica_nome_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinicas/logo/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/'),
        ),
        migrations.CreateModel(
            name='ClinicaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='clinicas/capa/')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='odontoPro.clinica')),
            ],
            options={
                'verbose_name': 'Imagem da Clínica',
                'verbose_name_plural': 'Imagens da Clínica',
                'ordering': ['ordem'],
            },
        ),
    ]
