# Generated by Django 5.2.10 on 2026-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0011_add_descricao_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='imagem',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='clinicas/'),
        ),
    ]
