# Generated by Django 5.2.10 on 2026-08-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0012_alter_clinica_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaimagem',
            name='imagem',
            field=models.ImageField(max_length=1024, upload_to='clinicas/capa/'),
        ),
    ]
