# Generated by Django 5.2.10 on 2026-02-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0013_permissao_gerenciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
