# Generated by Django 5.2.10 on 2026-02-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoPro', '0014_clinica_email_clinica_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerenciamento',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gerentes', to='odontoPro.clinica'),
            preserve_default=False,
        ),
    ]
